use_frameworks!

target 'AIMJSONModelNetworking-iOS_Example' do
  pod 'AIMJSONModelNetworking-iOS', :path => '../'

  target 'AIMJSONModelNetworking-iOS_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
